let movies = [
    {
        "title": "Nyckeln till frihet",
        "year": "1994",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            8,
            8,
            6,
            10,
            2,
            3,
            4,
            5,
            4,
            9,
            3,
            9,
            6,
            10,
            4,
            8,
            10,
            1,
            2,
            8,
            1,
            9,
            5,
            4,
            4,
            2,
            4,
            6,
            9,
            10
        ],
        "poster": "MV5BODU4MjU4NjIwNl5BMl5BanBnXkFtZTgwMDU2MjEyMDE@._V1_SY500_CR0,0,336,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT142M",
        "releaseDate": "1995-03-03",
        "averageRating": 0,
        "originalTitle": "The Shawshank Redemption",
        "storyline": "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.                Written by\nJ-S-Golden",
        "actors": [
            "Tim Robbins",
            "Morgan Freeman",
            "Bob Gunton"
        ],
        "imdbRating": 9.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BODU4MjU4NjIwNl5BMl5BanBnXkFtZTgwMDU2MjEyMDE@._V1_SY500_CR0,0,336,500_AL_.jpg"
    },
    {
        "title": "Gudfadern",
        "year": "1972",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            6,
            10,
            4,
            10,
            1,
            3,
            7,
            2,
            3,
            3,
            3,
            4,
            2,
            5,
            6,
            9,
            10,
            8,
            7,
            4,
            8,
            9,
            9,
            10,
            4,
            6,
            2,
            9,
            7,
            7
        ],
        "poster": "MV5BZTRmNjQ1ZDYtNDgzMy00OGE0LWE4N2YtNTkzNWQ5ZDhlNGJmL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,352,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT175M",
        "releaseDate": "1972-09-27",
        "averageRating": 0,
        "originalTitle": "The Godfather",
        "storyline": "When the aging head of a famous crime family decides to transfer his position to one of his subalterns, a series of unfortunate events start happening to the family, and a war begins between all the well-known families leading to insolence, deportation, murder and revenge, and ends with the favorable successor being finally chosen.                Written by\nJ. S. Golden",
        "actors": [
            "Marlon Brando",
            "Al Pacino",
            "James Caan"
        ],
        "imdbRating": 9.2,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZTRmNjQ1ZDYtNDgzMy00OGE0LWE4N2YtNTkzNWQ5ZDhlNGJmL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,352,500_AL_.jpg"
    },
    {
        "title": "Gudfadern del II",
        "year": "1974",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            2,
            5,
            1,
            1,
            8,
            4,
            2,
            3,
            10,
            10,
            4,
            9,
            8,
            9,
            7,
            6,
            6,
            9,
            9,
            4,
            1,
            8,
            4,
            5,
            7,
            7,
            7,
            1,
            10,
            6
        ],
        "poster": "MV5BMjZiNzIxNTQtNDc5Zi00YWY1LThkMTctMDgzYjY4YjI1YmQyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,351,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT202M",
        "releaseDate": "1975-07-28",
        "averageRating": 0,
        "originalTitle": "The Godfather: Part II",
        "storyline": "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.                Written by\nKeith Loh <loh@sfu.ca>",
        "actors": [
            "Al Pacino",
            "Robert De Niro",
            "Robert Duvall"
        ],
        "imdbRating": 9.0,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjZiNzIxNTQtNDc5Zi00YWY1LThkMTctMDgzYjY4YjI1YmQyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,351,500_AL_.jpg"
    },
    {
        "title": "The Dark Knight",
        "year": "2008",
        "genres": [
            "Action",
            "Crime",
            "Drama"
        ],
        "ratings": [
            3,
            6,
            4,
            1,
            6,
            10,
            6,
            3,
            5,
            9,
            1,
            3,
            1,
            7,
            8,
            10,
            6,
            2,
            8,
            6,
            7,
            1,
            4,
            3,
            8,
            3,
            10,
            8,
            10,
            4
        ],
        "poster": "MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT152M",
        "releaseDate": "2008-07-25",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Set within a year after the events of Batman Begins, Batman, Lieutenant James Gordon, and new district attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City until a mysterious and sadistic criminal mastermind known only as the Joker appears in Gotham, creating a new wave of chaos. Batman's struggle against the Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent and Rachel Dawes.                Written by\nLeon Lombardi",
        "actors": [
            "Christian Bale",
            "Heath Ledger",
            "Aaron Eckhart"
        ],
        "imdbRating": 9.0,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "title": "12 edsvurna m\u00e4n",
        "year": "1957",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            3,
            5,
            3,
            3,
            10,
            3,
            4,
            1,
            6,
            10,
            2,
            8,
            4,
            6,
            8,
            6,
            1,
            10,
            4,
            5,
            9,
            3,
            2,
            4,
            8,
            10,
            10,
            7,
            9,
            6
        ],
        "poster": "MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT96M",
        "releaseDate": "1957-07-29",
        "averageRating": 0,
        "originalTitle": "12 Angry Men",
        "storyline": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other. Based on the play, all of the action takes place on the stage of the jury room.                Written by\npjk <PETESID@VNET.IBM.COM>",
        "actors": [
            "Henry Fonda",
            "Lee J. Cobb",
            "Martin Balsam"
        ],
        "imdbRating": 8.9,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SY500_CR0,0,333,500_AL_.jpg"
    },
    {
        "title": "Schindler's List",
        "year": "1993",
        "genres": [
            "Biography",
            "Drama",
            "History"
        ],
        "ratings": [
            2,
            6,
            7,
            8,
            8,
            6,
            2,
            4,
            6,
            2,
            3,
            3,
            5,
            9,
            5,
            10,
            9,
            5,
            5,
            2,
            10,
            4,
            8,
            7,
            4,
            10,
            2,
            10,
            4,
            10
        ],
        "poster": "MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT195M",
        "releaseDate": "1994-03-04",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Oskar Schindler is a vainglorious and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.                Written by\nHarald Mayr <marvin@bike.augusta.de>",
        "actors": [
            "Liam Neeson",
            "Ralph Fiennes",
            "Ben Kingsley"
        ],
        "imdbRating": 8.9,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,333,500_AL_.jpg"
    },
    {
        "title": "Pulp Fiction",
        "year": "1994",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            2,
            9,
            7,
            7,
            7,
            2,
            2,
            4,
            1,
            9,
            6,
            3,
            4,
            10,
            8,
            6,
            7,
            5,
            9,
            4,
            3,
            5,
            9,
            3,
            8,
            2,
            6,
            7,
            4,
            4
        ],
        "poster": "MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SY500_CR0,0,336,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT154M",
        "releaseDate": "1994-11-25",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his weight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.                Written by\nSoumitra",
        "actors": [
            "John Travolta",
            "Uma Thurman",
            "Samuel L. Jackson"
        ],
        "imdbRating": 8.9,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SY500_CR0,0,336,500_AL_.jpg"
    },
    {
        "title": "Sagan om konungens \u00e5terkomst",
        "year": "2003",
        "genres": [
            "Adventure",
            "Drama",
            "Fantasy"
        ],
        "ratings": [
            6,
            3,
            2,
            7,
            5,
            2,
            10,
            10,
            4,
            5,
            7,
            1,
            8,
            4,
            8,
            7,
            2,
            8,
            5,
            5,
            6,
            3,
            3,
            10,
            10,
            2,
            1,
            8,
            3,
            5
        ],
        "poster": "MV5BYWY1ZWQ5YjMtMDE0MS00NWIzLWE1M2YtODYzYTk2OTNlYWZmXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SY500_SX334_AL_.jpg",
        "contentRating": "11",
        "duration": "PT201M",
        "releaseDate": "2003-12-17",
        "averageRating": 0,
        "originalTitle": "The Lord of the Rings: The Return of the King",
        "storyline": "The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Hobbits Frodo and Sam reach Mordor in their quest to destroy the \"one ring\", while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.                Written by\nJwelch5742",
        "actors": [
            "Elijah Wood",
            "Viggo Mortensen",
            "Ian McKellen"
        ],
        "imdbRating": 8.9,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYWY1ZWQ5YjMtMDE0MS00NWIzLWE1M2YtODYzYTk2OTNlYWZmXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SY500_SX334_AL_.jpg"
    },
    {
        "title": "Den gode, den onde, den fule",
        "year": "1966",
        "genres": [
            "Western"
        ],
        "ratings": [
            2,
            7,
            2,
            2,
            3,
            2,
            4,
            7,
            10,
            7,
            7,
            7,
            2,
            3,
            8,
            8,
            6,
            3,
            6,
            4,
            8,
            7,
            9,
            1,
            10,
            2,
            4,
            10,
            3,
            8
        ],
        "poster": "MV5BOTQ5NDI3MTI4MF5BMl5BanBnXkFtZTgwNDQ4ODE5MDE@._V1_SY500_CR0,0,328,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT161M",
        "releaseDate": "1968-04-10",
        "averageRating": 0,
        "originalTitle": "Il buono, il brutto, il cattivo",
        "storyline": "Blondie (The Good) is a professional gunslinger who is out trying to earn a few dollars. Angel Eyes (The Bad) is a hit man who always commits to a task and sees it through, as long as he is paid to do so. And Tuco (The Ugly) is a wanted outlaw trying to take care of his own hide. Tuco and Blondie share a partnership together making money off Tuco's bounty, but when Blondie unties the partnership, Tuco tries to hunt down Blondie. When Blondie and Tuco come across a horse carriage loaded with dead bodies, they soon learn from the only survivor (Bill Carson) that he and a few other men have buried a stash of gold in a cemetery. Unfortunately Carson dies and Tuco only finds out the name of the cemetery, while Blondie finds out the name on the grave. Now the two must keep each other alive in order to find the gold. Angel Eyes (who had been looking for Bill Carson) discovers that Tuco and Blondie met with Carson and knows they know the location of the gold. All he needs is for the two to ...                Written by\nJeremy Thomson",
        "actors": [
            "Clint Eastwood",
            "Eli Wallach",
            "Lee Van Cleef"
        ],
        "imdbRating": 8.9,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTQ5NDI3MTI4MF5BMl5BanBnXkFtZTgwNDQ4ODE5MDE@._V1_SY500_CR0,0,328,500_AL_.jpg"
    },
    {
        "title": "Fight Club",
        "year": "1999",
        "genres": [
            "Drama"
        ],
        "ratings": [
            6,
            5,
            10,
            10,
            6,
            6,
            6,
            7,
            2,
            8,
            10,
            2,
            3,
            5,
            1,
            3,
            10,
            3,
            6,
            2,
            6,
            2,
            10,
            4,
            4,
            8,
            9,
            10,
            10,
            5
        ],
        "poster": "MV5BZGY5Y2RjMmItNDg5Yy00NjUwLThjMTEtNDc2OGUzNTBiYmM1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX290_CR0,0,290,429_AL_.jpg",
        "contentRating": "15",
        "duration": "PT139M",
        "releaseDate": "1999-12-25",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler's fight club, he must accept the awful truth that Tyler may not be who he says he is.                Written by\nRhiannon",
        "actors": [
            "Brad Pitt",
            "Edward Norton",
            "Meat Loaf"
        ],
        "imdbRating": 8.8,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZGY5Y2RjMmItNDg5Yy00NjUwLThjMTEtNDc2OGUzNTBiYmM1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX290_CR0,0,290,429_AL_.jpg"
    },
    {
        "title": "Yojimbo (Livvakten)",
        "year": "1961",
        "genres": [
            "Action",
            "Drama",
            "Thriller"
        ],
        "ratings": [
            10,
            9,
            8,
            9,
            9,
            1,
            1,
            2,
            6,
            4,
            8,
            2,
            2,
            9,
            7,
            10,
            2,
            7,
            3,
            5,
            9,
            3,
            8,
            6,
            6,
            3,
            2,
            10,
            1,
            3
        ],
        "poster": "MV5BZThiZjAzZjgtNDU3MC00YThhLThjYWUtZGRkYjc2ZWZlOTVjXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SY500_CR0,0,332,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT110M",
        "releaseDate": "1964-10-28",
        "averageRating": 0,
        "originalTitle": "Y\u00f4jinb\u00f4",
        "storyline": "Sanjuro, a wandering samurai enters a rural town in nineteenth century Japan. After learning from the innkeeper that the town is divided between two gangsters, he plays one side off against the other. His efforts are complicated by the arrival of the wily Unosuke, the son of one of the gangsters, who owns a revolver. Unosuke has Sanjuro beaten after he reunites an abducted woman with her husband and son, then massacres his father's opponents. During the slaughter, the samurai escapes with the help of the innkeeper; but while recuperating at a nearby temple, he learns of innkeeper's abduction by Unosuke, and returns to the town to confront him.                Written by\nBernard Keane <BKeane2@email.dot.gov.au>",
        "actors": [
            "Toshir\u00f4 Mifune",
            "Eijir\u00f4 T\u00f4no",
            "Tatsuya Nakadai"
        ],
        "imdbRating": 8.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZThiZjAzZjgtNDU3MC00YThhLThjYWUtZGRkYjc2ZWZlOTVjXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SY500_CR0,0,332,500_AL_.jpg"
    },
    {
        "title": "Batman Begins",
        "year": "2005",
        "genres": [
            "Action",
            "Adventure"
        ],
        "ratings": [
            2,
            5,
            2,
            8,
            1,
            2,
            9,
            5,
            10,
            3,
            7,
            7,
            7,
            4,
            8,
            2,
            10,
            6,
            6,
            3,
            7,
            8,
            3,
            7,
            10,
            5,
            8,
            2,
            9,
            4
        ],
        "poster": "MV5BNTM3OTc0MzM2OV5BMl5BanBnXkFtZTYwNzUwMTI3._V1_SY360_CR0,0,242,360_AL_.jpg",
        "contentRating": "11",
        "duration": "PT140M",
        "releaseDate": "2005-07-27",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "When his parents are killed, billionaire playboy Bruce Wayne relocates to Asia where he is mentored by Henri Ducard and Ra's Al Ghul in how to fight evil. When learning about the plan to wipe out evil in Gotham City by Ducard, Bruce prevents this plan from getting any further and heads back to his home. Back in his original surroundings, Bruce adopts the image of a bat to strike fear into the criminals and the corrupt as the icon known as 'Batman'. But it doesn't stay quiet for long.                Written by\nkonstantinwe",
        "actors": [
            "Christian Bale",
            "Michael Caine",
            "Ken Watanabe"
        ],
        "imdbRating": 8.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTM3OTc0MzM2OV5BMl5BanBnXkFtZTYwNzUwMTI3._V1_SY360_CR0,0,242,360_AL_.jpg"
    },
    {
        "title": "Upp",
        "year": "2009",
        "genres": [
            "Animation",
            "Adventure",
            "Comedy"
        ],
        "ratings": [
            4,
            1,
            7,
            1,
            5,
            7,
            9,
            9,
            10,
            2,
            9,
            7,
            10,
            9,
            7,
            2,
            6,
            1,
            6,
            6,
            1,
            2,
            3,
            5,
            2,
            7,
            5,
            10,
            7,
            5
        ],
        "poster": "MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SY500_CR0,0,332,500_AL_.jpg",
        "contentRating": "7",
        "duration": "PT96M",
        "releaseDate": "2009-10-16",
        "averageRating": 0,
        "originalTitle": "Up",
        "storyline": "Carl Fredricksen as a boy wanted to explore South America and find the forbidden Paradise Falls. About 64 years later he gets to begin his journey along with a Boy Scout named Russel with help from 500 balloons. On their journey they discover many new friends including a talking dog and Carl and Russel figure out that someone evil plans. Carl soon realizes that this evildoer is his childhood idol. Will they be able to defeat him and will they find Paradise Falls?",
        "actors": [
            "Edward Asner",
            "Jordan Nagai",
            "John Ratzenberger"
        ],
        "imdbRating": 8.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SY500_CR0,0,332,500_AL_.jpg"
    },
    {
        "title": "I hetaste laget",
        "year": "1959",
        "genres": [
            "Comedy",
            "Romance"
        ],
        "ratings": [
            5,
            5,
            7,
            5,
            2,
            7,
            2,
            8,
            4,
            6,
            2,
            1,
            4,
            5,
            2,
            8,
            2,
            1,
            1,
            8,
            5,
            8,
            9,
            8,
            4,
            4,
            10,
            7,
            6,
            2
        ],
        "poster": "MV5BNzAyOGIxYjAtMGY2NC00ZTgyLWIwMWEtYzY0OWQ4NDFjOTc5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,322,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT120M",
        "releaseDate": "1959-09-28",
        "averageRating": 0,
        "originalTitle": "Some Like It Hot",
        "storyline": "When two Chicago musicians, Joe and Jerry, witness the the St. Valentine's Day massacre, they want to get out of town and get away from the gangster responsible, Spats Colombo. They're desperate to get a gig out of town but the only job they know of is in an all-girl band heading to Florida. They show up at the train station as Josephine and Daphne, the replacement saxophone and bass players. They certainly enjoy being around the girls, especially Sugar Kane Kowalczyk who sings and plays the ukulele. Joe in particular sets out to woo her while Jerry/Daphne is wooed by a millionaire, Osgood Fielding III. Mayhem ensues as the two men try to keep their true identities hidden and Spats Colombo and his crew show up for a meeting with several other crime lords.                Written by\ngarykmcd",
        "actors": [
            "Marilyn Monroe",
            "Tony Curtis",
            "Jack Lemmon"
        ],
        "imdbRating": 8.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzAyOGIxYjAtMGY2NC00ZTgyLWIwMWEtYzY0OWQ4NDFjOTc5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,322,500_AL_.jpg"
    },
    {
        "title": "Sierra Madres skatt",
        "year": "1948",
        "genres": [
            "Adventure",
            "Drama",
            "Western"
        ],
        "ratings": [
            8,
            9,
            7,
            6,
            9,
            3,
            8,
            6,
            9,
            5,
            5,
            6,
            7,
            10,
            5,
            1,
            3,
            1,
            3,
            9,
            10,
            8,
            3,
            7,
            9,
            7,
            3,
            7,
            5,
            9
        ],
        "poster": "MV5BMTQ4MzUzOTYwOV5BMl5BanBnXkFtZTgwNDA4MzgyMjE@._V1_SY250_SX169_AL_.jpg",
        "contentRating": "",
        "duration": "PT126M",
        "releaseDate": "1948-04-29",
        "averageRating": 0,
        "originalTitle": "The Treasure of the Sierra Madre",
        "storyline": "Fred C. Dobbs and Bob Curtin, both down on their luck in Tampico, Mexico in 1925, meet up with a grizzled prospector named Howard and decide to join with him in search of gold in the wilds of central Mexico. Through enormous difficulties, they eventually succeed in finding gold, but bandits, the elements, and most especially greed threaten to turn their success into disaster.                Written by\nJim Beaver <jumblejim@prodigy.net>",
        "actors": [
            "Humphrey Bogart",
            "Walter Huston",
            "Tim Holt"
        ],
        "imdbRating": 8.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ4MzUzOTYwOV5BMl5BanBnXkFtZTgwNDA4MzgyMjE@._V1_SY250_SX169_AL_.jpg"
    },
    {
        "title": "De skoningsl\u00f6sa",
        "year": "1992",
        "genres": [
            "Drama",
            "Western"
        ],
        "ratings": [
            6,
            7,
            2,
            9,
            10,
            4,
            4,
            10,
            5,
            9,
            9,
            2,
            3,
            3,
            1,
            8,
            3,
            10,
            2,
            5,
            1,
            7,
            8,
            7,
            3,
            10,
            4,
            10,
            9,
            3
        ],
        "poster": "MV5BODM3YWY4NmQtN2Y3Ni00OTg0LWFhZGQtZWE3ZWY4MTJlOWU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,332,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT131M",
        "releaseDate": "1992-09-11",
        "averageRating": 0,
        "originalTitle": "Unforgiven",
        "storyline": "The town of Big Whisky is full of normal people trying to lead quiet lives. Cowboys try to make a living. Sheriff 'Little Bill' tries to build a house and keep a heavy-handed order. The town whores just try to get by.Then a couple of cowboys cut up a whore. Dissatisfied with Bill's justice, the prostitutes put a bounty on the cowboys. The bounty attracts a young gun billing himself as 'The Schofield Kid', and aging killer William Munny. Munny reformed for his young wife, and has been raising crops and two children in peace. But his wife is gone. Farm life is hard. And Munny is no good at it. So he calls his old partner Ned, saddles his ornery nag, and rides off to kill one more time, blurring the lines between heroism and villainy, man and myth.                Written by\nCharlie Ness",
        "actors": [
            "Clint Eastwood",
            "Gene Hackman",
            "Morgan Freeman"
        ],
        "imdbRating": 8.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BODM3YWY4NmQtN2Y3Ni00OTg0LWFhZGQtZWE3ZWY4MTJlOWU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,332,500_AL_.jpg"
    },
    {
        "title": "Underg\u00e5ngen - Hitler och Tredje rikets fall",
        "year": "2004",
        "genres": [
            "Biography",
            "Drama",
            "History"
        ],
        "ratings": [
            2,
            4,
            5,
            7,
            10,
            4,
            2,
            10,
            8,
            6,
            2,
            7,
            3,
            8,
            5,
            3,
            6,
            1,
            2,
            2,
            4,
            4,
            9,
            4,
            1,
            6,
            2,
            5,
            2,
            10
        ],
        "poster": "MV5BMTM1OTI1MjE2Nl5BMl5BanBnXkFtZTcwMTEwMzc4NA@@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT156M",
        "releaseDate": "2005-02-25",
        "averageRating": 0,
        "originalTitle": "Der Untergang",
        "storyline": "In April of 1945, Germany stands at the brink of defeat with the Soviet Armies closing in from the west and south. In Berlin, capital of the Third Reich, Adolf Hitler proclaims that Germany will still achieve victory and orders his Generals and advisers to fight to the last man. \"Downfall\" explores these final days of the Reich, where senior German leaders (such as Himmler and Goring) began defecting from their beloved Fuhrer, in an effort to save their own lives, while still others (Joseph Goebbels) pledge to die with Hitler. Hitler, himself, degenerates into a paranoid shell of a man, full of optimism one moment and suicidal depression the next. When the end finally does comes, and Hitler lies dead by his own hand, what is left of his military must find a way to end the killing that is the Battle of Berlin, and lay down their arms in surrender.                Written by\nAnthony Hughes {husnock31@hotmail.com}",
        "actors": [
            "Bruno Ganz",
            "Alexandra Maria Lara",
            "Ulrich Matthes"
        ],
        "imdbRating": 8.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM1OTI1MjE2Nl5BMl5BanBnXkFtZTcwMTEwMzc4NA@@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "title": "Tjuren fr\u00e5n Bronx",
        "year": "1980",
        "genres": [
            "Biography",
            "Drama",
            "Sport"
        ],
        "ratings": [
            3,
            10,
            8,
            1,
            5,
            4,
            9,
            5,
            9,
            2,
            8,
            3,
            2,
            6,
            3,
            5,
            10,
            2,
            1,
            9,
            3,
            9,
            4,
            10,
            3,
            3,
            10,
            6,
            9,
            3
        ],
        "poster": "MV5BMjIxOTg3OTc5MF5BMl5BanBnXkFtZTcwNzkwNjMwNA@@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT129M",
        "releaseDate": "1981-03-20",
        "averageRating": 0,
        "originalTitle": "Raging Bull",
        "storyline": "When Jake LaMotta steps into a boxing ring and obliterates his opponent, he's a prizefighter. But when he treats his family and friends the same way, he's a ticking time bomb, ready to go off at any moment. Though LaMotta wants his family's love, something always seems to come between them. Perhaps it's his violent bouts of paranoia and jealousy. This kind of rage helped make him a champ, but in real life, he winds up in the ring alone.                Written by\nalfiehitchie",
        "actors": [
            "Robert De Niro",
            "Cathy Moriarty",
            "Joe Pesci"
        ],
        "imdbRating": 8.2,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxOTg3OTc5MF5BMl5BanBnXkFtZTcwNzkwNjMwNA@@._V1_SY500_CR0,0,333,500_AL_.jpg"
    },
    {
        "title": "Den tredje mannen",
        "year": "1949",
        "genres": [
            "Film-Noir",
            "Mystery",
            "Thriller"
        ],
        "ratings": [
            7,
            7,
            1,
            7,
            6,
            9,
            10,
            8,
            9,
            8,
            10,
            1,
            8,
            5,
            7,
            8,
            2,
            2,
            5,
            10,
            1,
            4,
            8,
            7,
            2,
            5,
            2,
            9,
            6,
            2
        ],
        "poster": "MV5BZjQxYmRkMjgtMmZkZi00ZDYyLTk5OTktZWZjZTEzNGZlMWEwXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,335,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT104M",
        "releaseDate": "1949-10-26",
        "averageRating": 0,
        "originalTitle": "The Third Man",
        "storyline": "An out of work pulp fiction novelist, Holly Martins, arrives in a post war Vienna divided into sectors by the victorious allies, and where a shortage of supplies has lead to a flourishing black market. He arrives at the invitation of an ex-school friend, Harry Lime, who has offered him a job, only to discover that Lime has recently died in a peculiar traffic accident. From talking to Lime's friends and associates Martins soon notices that some of the stories are inconsistent, and determines to discover what really happened to Harry Lime.                Written by\nMark Thompson <mrt@oasis.icl.co.uk>",
        "actors": [
            "Orson Welles",
            "Joseph Cotten",
            "Alida Valli"
        ],
        "imdbRating": 8.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZjQxYmRkMjgtMmZkZi00ZDYyLTk5OTktZWZjZTEzNGZlMWEwXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,335,500_AL_.jpg"
    },
    {
        "title": "Die Hard",
        "year": "1988",
        "genres": [
            "Action",
            "Thriller"
        ],
        "ratings": [
            7,
            3,
            3,
            7,
            10,
            10,
            4,
            7,
            9,
            3,
            5,
            10,
            7,
            8,
            6,
            9,
            3,
            5,
            3,
            3,
            5,
            7,
            7,
            9,
            4,
            3,
            6,
            6,
            6,
            6
        ],
        "poster": "MV5BMzNmY2IwYzAtNDQ1NC00MmI4LThkOTgtZmVhYmExOTVhMWRkXkEyXkFqcGdeQXVyMTk5NDA3Nw@@._V1_SX290_CR0,0,290,429_AL_.jpg",
        "contentRating": "15",
        "duration": "PT131M",
        "releaseDate": "1988-09-30",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "NYPD cop John McClane goes on a Christmas vacation to visit his wife Holly in Los Angeles where she works for the Nakatomi Corporation. While they are at the Nakatomi headquarters for a Christmas party, a group of bank robbers led by Hans Gruber take control of the building and hold everyone hostage, with the exception of John, while they plan to perform a lucrative heist. Unable to escape and with no immediate police response, John is forced to take matters into his own hands.                Written by\nSam",
        "actors": [
            "Bruce Willis",
            "Alan Rickman",
            "Bonnie Bedelia"
        ],
        "imdbRating": 8.2,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzNmY2IwYzAtNDQ1NC00MmI4LThkOTgtZmVhYmExOTVhMWRkXkEyXkFqcGdeQXVyMTk5NDA3Nw@@._V1_SX290_CR0,0,290,429_AL_.jpg"
    }
]